pipelines:
  branches:
    master:
    - step:
        name: build and publish docker image
        services:
          - docker
        caches:
          - docker
        script:
          - docker build -f Api/Dockerfile -t $HEROKU_APP_NAME .
          - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          - docker tag $HEROKU_APP_NAME registry.heroku.com/$HEROKU_APP_NAME/web
          - docker push registry.heroku.com/$HEROKU_APP_NAME/web
          - docker inspect registry.heroku.com/$HEROKU_APP_NAME/web --format={{.Id}} > WEB_DOCKER_IMAGE_ID
        artifacts:
          - WEB_DOCKER_IMAGE_ID
    - step:
        name: deploy-to-heroku
        deployment: staging
        script:
          - export WEB_DOCKER_IMAGE_ID=$(cat WEB_DOCKER_IMAGE_ID)
          - chmod +x deploy.sh
          - ./deploy.sh
          - echo "Done..."

options:
  docker: true