version: '3.4'

services:
  ssnbackend:
    container_name: ssnbackend
    image: hub.manas.org/ssnbackend:prod
    restart: always
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - '5000:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Prod
      - DOTNET_ENVIRONMENT=Prod
    volumes:
      - static_files: /app/wwwroot
    
volumes:
  static_files:
