START TRANSACTION;

CREATE TABLE "RefreshTokens" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Token" text NULL,
    "Expires" timestamp without time zone NOT NULL,
    "Created" timestamp without time zone NOT NULL,
    "CreatedByIp" text NULL,
    "Revoked" timestamp without time zone NULL,
    "RevokedByIp" text NULL,
    "ReplacedByToken" text NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210403154357_RefreshToken', '5.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "Students" ADD "AuthKey" text NULL;

ALTER TABLE "Students" ADD "Firstname" text NULL;

ALTER TABLE "Students" ADD "Lastname" text NULL;

CREATE UNIQUE INDEX "IX_Institutes_Name" ON "Institutes" ("Name");

CREATE UNIQUE INDEX "IX_Departments_Name" ON "Departments" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210405161835_SomeUpdates', '5.0.4');

COMMIT;

START TRANSACTION;

CREATE UNIQUE INDEX "IX_Students_StudentNumber" ON "Students" ("StudentNumber");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210405183851_UniqueStudentNumber', '5.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "Students" DROP CONSTRAINT "FK_Students_Users_UserId";

ALTER TABLE "Students" ALTER COLUMN "UserId" DROP NOT NULL;

ALTER TABLE "Students" ADD CONSTRAINT "FK_Students_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210407180944_StudentsChanged', '5.0.4');

COMMIT;

