START TRANSACTION;

CREATE TABLE "Posts" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Body" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDraft" boolean NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_Posts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Posts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Comments" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Body" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone NOT NULL,
    "UserId" text NOT NULL,
    "PostId" integer NULL,
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Comments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PostLikes" (
    "UserId" text NOT NULL,
    "PostId" integer NOT NULL,
    CONSTRAINT "PK_PostLikes" PRIMARY KEY ("UserId", "PostId"),
    CONSTRAINT "FK_PostLikes_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PostLikes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PostPictures" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Url" text NOT NULL,
    "PostId" integer NOT NULL,
    CONSTRAINT "PK_PostPictures" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PostPictures_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Tags" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "PostId" integer NULL,
    CONSTRAINT "PK_Tags" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tags_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "CommentLikes" (
    "UserId" text NOT NULL,
    "CommentId" integer NOT NULL,
    CONSTRAINT "PK_CommentLikes" PRIMARY KEY ("UserId", "CommentId"),
    CONSTRAINT "FK_CommentLikes_Comments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "Comments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CommentLikes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CommentReplies" (
    "ReplyId" integer NOT NULL,
    "TargetId" integer NOT NULL,
    CONSTRAINT "PK_CommentReplies" PRIMARY KEY ("TargetId", "ReplyId"),
    CONSTRAINT "FK_CommentReplies_Comments_ReplyId" FOREIGN KEY ("ReplyId") REFERENCES "Comments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CommentReplies_Comments_TargetId" FOREIGN KEY ("TargetId") REFERENCES "Comments" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PostComments" (
    "PostId" integer NOT NULL,
    "CommentId" integer NOT NULL,
    CONSTRAINT "PK_PostComments" PRIMARY KEY ("PostId", "CommentId"),
    CONSTRAINT "FK_PostComments_Comments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "Comments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PostComments_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PostTags" (
    "PostId" integer NOT NULL,
    "TagId" integer NOT NULL,
    CONSTRAINT "PK_PostTags" PRIMARY KEY ("PostId", "TagId"),
    CONSTRAINT "FK_PostTags_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PostTags_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES "Tags" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CommentLikes_CommentId" ON "CommentLikes" ("CommentId");

CREATE UNIQUE INDEX "IX_CommentReplies_ReplyId" ON "CommentReplies" ("ReplyId");

CREATE INDEX "IX_Comments_PostId" ON "Comments" ("PostId");

CREATE INDEX "IX_Comments_UserId" ON "Comments" ("UserId");

CREATE UNIQUE INDEX "IX_PostComments_CommentId" ON "PostComments" ("CommentId");

CREATE INDEX "IX_PostLikes_PostId" ON "PostLikes" ("PostId");

CREATE INDEX "IX_PostPictures_PostId" ON "PostPictures" ("PostId");

CREATE INDEX "IX_Posts_UserId" ON "Posts" ("UserId");

CREATE INDEX "IX_PostTags_TagId" ON "PostTags" ("TagId");

CREATE INDEX "IX_Tags_PostId" ON "Tags" ("PostId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210502160325_PostsAdded', '5.0.5');

COMMIT;

